version: '3.7'
services:
  mysql:
    image: mysql:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
