version: '3.9'

services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - crsa_network
    restart: always

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - crsa_network

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - crsa_network
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/etc/prometheus
    networks:
      - crsa_network

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - crsa_network
    depends_on:
      - prometheus

#  crsa-app:
#    image: squarebricks/crsa:latest
#    ports:
#      - "8443:8443"
#    environment:
#      REDIS_HOST: redis-stack
#      REDIS_PORT: 6379
#      RABBITMQ_ADDRESSES: rabbitmq
#    restart: always
#    networks:
#      - crsa_network
#    depends_on:
#      - redis-stack
#      - mysql
#      - rabbitmq

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: C:/Users/rjanapureddy/Docker/mysql
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: C:/Users/rjanapureddy/Docker/redis-stack
      o: bind
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      device: C:/Users/rjanapureddy/Docker/rabbitmq
      o: bind
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Users/rjanapureddy/Docker/prometheus
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Users/rjanapureddy/Docker/grafana

networks:
  crsa_network:
