spring:
  jpa:
    generate-ddl: 'true'
    database: default
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
      max_allowed_packet: '2000'
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/crsa?createDatabaseIfNotExist=true
    password: password
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: '600000'
