spring:
  security:
    user:
      name: user
      password: user
      roles:
        - CRSA_USER_WRITE
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  http2:
    enabled: true
  port: 8443
  ssl:
    enabled: true
    key-alias: spring-https
    key-store: classpath:spring-https.p12
    key-store-type: PKCS12
    key-password: password
    key-store-password: password
