global:
  scrape_interval: 15s # How frequently to scrape metrics
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'crsa'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['192.168.77.20:8443']
    tls_config:
      insecure_skip_verify: true
